name: Frontend CI/CD + PROD

# --- TRIGGERS WORKFLOWS ---
on:
  push:
    branches:
      - deploy # Executa quan es fa push a deploy
  pull_request:     # <--- Afegeix aquest bloc
    branches:
      - deploy  # S'executa quan obres una PR que apunta CAP a deploy
  workflow_dispatch: # Permet executar-ho manualment des de la web de GitHub

jobs:
  # --- Primer de tot executar els tests ---
  test-frontend:
    name: Tests frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend # Ens situem a la carpeta del frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Baixa el codi del repositori

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build frontend for e2e tests
        run: npm run build

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run frontend unit tests
        run: npm run test:unit

      - name: Run frontend end-to-end tests
        run: npm run test:e2e
  # TESTS BACKEND
  test-backend:
    name: Tests backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend 

    steps:
      - name: Checkout del repositori
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json 

      - name: Instal·lar dependències backend
        run: npm ci

      - name: Executar tests backend
        run: npm test
        env:
          MONGO_URI: ${{ secrets.MONGO_URI_TEST }}

  # --- Si passen els tests, fer build deploy del frontend ---
  build_and_deploy_job:
    name: Build i deploy frontend a Production
    runs-on: ubuntu-latest
    needs: 
        - test-frontend
        - test-backend
    if: github.ref == 'refs/heads/deploy'
    permissions:
       id-token: write
       contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
           script: |
               const coredemo = require('@actions/core')
               return await coredemo.getIDToken()
           result-encoding: string
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_BAY_0F8F41603 }}
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./frontend" # App source code path
          api_location: "https://backend-deploy-huc8btfyd7dqcdby.francecentral-01.azurewebsites.net" # Api source code path - optional
          app_build_command: "npm run build -- --mode production"
          output_location: "dist" # Built app content directory - optional
          github_id_token: ${{ steps.idtoken.outputs.result }}
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_BAY_0F8F41603 }}
          action: "close"
          app_location: "./frontend"
          output_location: "dist"
