name: Backend CI/CD

# --- TRIGGERS WORKFLOWS ---
on:
  push:
    branches:
      - dev # Executa quan es fa push a dev
      - pre_deploy # Executa quan es fa push a pre_deploy
      - deploy # Executa quan es fa push a deploy
  workflow_dispatch: # Permet executar-ho manualment des de la web de GitHub

jobs:
  # --- Primer de tot executar els tests ---
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend # Ens situem a la carpeta del backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Baixa el codi del repositori

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run backend tests
        run: npm test
        env:
          MONGO_URI: ${{ secrets.MONGO_URI_TEST }}

  # --- Si passen els tests, fer deploy del backend ---
  deploy-backend:
    needs: test-backend # <--- Si test-backend falla no s'executa
    if: github.ref != 'refs/heads/dev'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build application (optional)
        run: npm run build --if-present

      - name: Archive app artifact
        run: zip -r ../backend.zip .

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_21B4D4B0ACEE4977A3C6D485136331B1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7B5EB4F1FF044DFFB6C157F1CE4C3A5F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A6BC006E20484AFCBBB127E781CFC65B }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: registre-backend
          slot-name: Production
          package: backend.zip
