name: Tests Dev CI/CD

# --- TRIGGERS WORKFLOWS ---
on:
  push:
    branches:
      - dev # Executa quan es fa push a pre_deploy
  workflow_dispatch: # Permet executar-ho manualment des de la web de GitHub

jobs:
  # --- Tests Frontend ---
  test-frontend:
    name: Tests frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend # Ens situem a la carpeta del frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Baixa el codi del repositori

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build frontend for e2e tests
        run: npm run build

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run frontend unit tests
        run: npm run test:coverage

      - name: Run Cypress E2E tests
        run: npm run e2e:ci
        
  # TESTS BACKEND
  test-backend:
    name: Tests backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend 

    steps:
      - name: Checkout del repositori
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json 

      - name: Instal·lar dependències backend
        run: npm ci

      - name: Executar tests backend
        run: npm test
        env:
          MONGO_URI: ${{ secrets.MONGO_URI_TEST }}